export const UPSCALER_KEY_PREFIX = 'upscaler:'; // Prefix for user's daily upscale usage in KV store
export const GENERATOR_KEY_PREFIX = 'generator:'; // Prefix for user's daily image generation usage in KV store
export const ENHANCE_PROMPT_KEY_PREFIX = 'enhance_prompt:'; // New prefix for prompt enhancement
export const TOTAL_GENERATOR_KEY_PREFIX = 'generator_total_usage:'; // Prefix for total images generated by user
export const TOTAL_UPSCALER_KEY_PREFIX = 'upscaler_total_usage:'; // Prefix for total images upscaled by user
export const TOTAL_ENHANCE_PROMPT_KEY_PREFIX = 'enhance_prompt_total_usage:'; // New prefix for total prompt enhancements
export const UPSCALER_DAILY_LIMIT = 20;
export const GENERATOR_DAILY_LIMIT = 20;
export const ENHANCE_PROMPT_DAILY_LIMIT = 5; // New daily limit for prompt enhancement

// Pro plan constants
export const PRO_UPSCALER_MONTHLY_LIMIT = 1000;
export const PRO_GENERATOR_MONTHLY_LIMIT = 1000;
export const PRO_ENHANCE_PROMPT_MONTHLY_LIMIT = Infinity; // Unlimited

// Pro plan key prefixes
export const PRO_UPSCALER_KEY_PREFIX = 'pro_upscaler:';
export const PRO_GENERATOR_KEY_PREFIX = 'pro_generator:';
export const PRO_ENHANCE_PROMPT_KEY_PREFIX = 'pro_enhance_prompt:';