export const UPSCALER_KEY_PREFIX = 'upscaler:'; // Prefix for user's daily upscale usage in KV store
export const GENERATOR_KEY_PREFIX = 'generator:'; // Prefix for user's daily image generation usage in KV store
export const TOTAL_GENERATOR_KEY_PREFIX = 'generator_total_usage:'; // Prefix for total images generated by user
export const TOTAL_UPSCALER_KEY_PREFIX = 'upscaler_total_usage:'; // Prefix for total images upscaled by user
export const UPSCALER_DAILY_LIMIT = 20;
export const GENERATOR_DAILY_LIMIT = 20;